import { useEffect } from 'react';
import { Link } from 'react-router-dom';
import { useNotifications } from '../../context/notificationContext';
export default function Notifications() {
  const { notifications: items, ready, connected, hasMore, loadingMore, loadMore, markAllRead } = useNotifications();
  useEffect(() => { if (ready) markAllRead().catch(() => {}); }, [ready, markAllRead]);
  const words = { like: 'liked your story', comment: 'commented on your story', follow: 'started following you', bookmark: 'saved your story', share: 'shared your story' };
  return <main className="min-h-screen bg-gradient-to-br from-violet-50 to-rose-50 px-3 py-6 sm:px-4 sm:py-12"><section className="mx-auto max-w-3xl overflow-hidden rounded-3xl bg-white shadow-xl"><header className="bg-gradient-to-r from-violet-700 to-fuchsia-600 p-6 text-white sm:p-8"><p className="text-sm font-bold uppercase tracking-widest text-white/70">Your activity · {connected ? 'live' : 'reconnecting'}</p><h1 className="mt-2 text-3xl font-black">Notifications</h1></header>{!ready ? <p className="p-10 text-center text-gray-500">Loading your activity…</p> : !items.length ? <p className="p-10 text-center text-gray-500">You’re all caught up. New likes, saves, shares, comments, and followers will appear here.</p> : <div className="max-h-[75vh] divide-y overflow-y-auto">{items.map((item) => <Link key={item._id} to={item.story ? `/share/${item.story}` : item.actor?._id ? `/creator/${item.actor._id}` : '/'} className={`flex items-center gap-3 p-4 transition hover:bg-violet-50 sm:gap-4 sm:p-5 ${item.read ? '' : 'bg-violet-50/60'}`}><img src={item.actor?.avatar || `https://ui-avatars.com/api/?name=${encodeURIComponent(item.actor?.username || 'Reader')}&background=6d28d9&color=fff`} alt="" className="h-10 w-10 shrink-0 rounded-full object-cover sm:h-11 sm:w-11"/><div className="min-w-0 flex-1"><p className="text-sm text-gray-800"><b>@{item.actor?.username || 'Someone'}</b> {words[item.type] || item.message}</p><p className="mt-1 text-xs text-gray-400">{new Date(item.createdAt).toLocaleString()}</p></div>{!item.read && <span className="h-2.5 w-2.5 shrink-0 rounded-full bg-violet-600" />}</Link>)}</div>}{ready && hasMore && <div className="border-t p-4 text-center"><button onClick={() => loadMore().catch(() => {})} disabled={loadingMore} className="rounded-xl bg-violet-50 px-5 py-3 text-sm font-bold text-violet-700 hover:bg-violet-100 disabled:opacity-50">{loadingMore ? 'Loading…' : 'Load older notifications'}</button></div>}</section></main>;
}
